travis:
  secure:
    BINSTAR_TOKEN: Q2adveSFA6nZcDzXoX3i/gqQK2dGCSTYmsxIsz5GNhTYpZET5JA0589eKPu1YLtbHBpEYD+Mc5wB8T9TdMB2maFSrrgB+q0FHRnSpH+VwhVC/DNztSO1Z03/aFJ1065pzG8+JK1HYfEdXb9Le1/KKLpEJZuU8YxIEMg0bIBsslonVxKwNdXdk2dw3YHrPjz+/cMoefOCj4Gr7Dm+sxIbT7n/ImN7lprMQ+FaigPmn0PbLXPZmSAbdJEwpwzJlyQYrSNQxjuPl5C4jl/MmC9XoxJTukvnal/FmMGgUrfMMCgcQez7D2APLoIVCKhDRk5KlJ0+Ulq+mSU5Ezbw2S0Kpp/ogRdgJoeX2wzg6v19EE7U2EwSm5szfMXUuhgmfMjGc5E8IvXEP4b4P1v9KYo/WS3awmtmpIIsg1RthhfO9FRnpspHvI4YbAYOw8Ui3l3XjsEcqHzPOqFQGliwks/ZOVKQR7ejFtd5VyYrv9UHaXSugT3SftIHlWaFsrv+yi9TQipenIWCURFpHw5FVm2y8wEgfvRP2NrIwty+6iiXHKejDimemlBCrAI/ISXTaZD117b/BgnkyV8dOceSQRqwPrhXKt/wuUHp7zjXS22tGUDyhG5/LhUs44eT2DPQMjB9eTQJKp6rOecBU6E57QyZWox9N13Y4zUv5iLFiPdfU8A=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
